# Generated by Django 3.2.9 on 2021-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonDomainOnlyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonOnlyBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonOnlyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
    ]
